version: "3"
services:

  message:
    build: message/
    ports:
      - "9011:9011"
    depends_on:
      - messageapp
      - mongodb_message
      - replica_message
      - redis

  credit:
    build: credit/
    ports:
      - "9006:9006"
    depends_on:
      - mongodb_credit
      - replica_credit
      - redis

  messageapp:
    image: cabify/backend-bootcamp-messageapp:exercise10
    ports:
      - "3000:3000"

  mongodb_credit:
    image: mongo
    command: mongod --port 27018    
    volumes:
      - ./credit/data/db:/credit/data/db
    ports:
      - 27018:27018

  replica_credit:
    image: mongo
    command: mongod --port 27019    
    volumes:
      - ./credit/data/replica:/credit/data/replica
    ports:
      - 27019:27019

  mongodb_message:
    image: mongo
    command: mongod --port 27027
    volumes:
      - ./message/data/db:/message/data/db
    ports:
      - 27027:27027

  replica_message:
    image: mongo
    command: mongod --port 27028
    volumes:
      - ./message/data/replica:/message/data/replica
    ports:
      - 27028:27028

  redis:
    image: redis
    ports:
      - 6379:6379

  prometheus:
   image: prom/prometheus:v2.1.0
   volumes:
     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
   ports:
     - 9090:9090
     
  grafana:
   image: grafana/grafana:5.1.0
   ports:
    - "3030:3000"
   volumes:
     - ./grafana.ini:/etc/grafana/grafana.ini
